$APIKEY = "YOUR-API-KEY-HERE"
$IMAGESAVEPATH = "YOUR-IMAGE-SAVE-PATH-HERE"

$ALTSAVEPATH = "YOUR-ALT-SAVE-PATH-HERE"
$EXPLANATIONHTMLSAVEPATH = "YOUR-EXPLANATION-SAVE-PATH-HERE"

$url = "https://science.nasa.gov/wp-json/wp/v2/apod-basic/?count=1&api_key=$APIKEY"
